#!/usr/bin/env bash
# session-end-check.sh — SessionEnd hook (v0.9.27 R-N10).
#
# Mechanizes core §11 "Session-exit mid-SPINE" HARD self-rule. At session
# termination, scan the transcript JSONL for mutation tool_use entries
# (Edit / Write / NotebookEdit) since the last user-input message, and
# count VALIDATE signals (Bash with test-runner / lint / typecheck /
# git commit / git push patterns). If mutations > 0 AND validates == 0:
# write a `<cwd>/tasks/<slug>-paused.md` checkpoint, stderr a one-line
# warn, and append a `warn` row to rule-hits.jsonl under §11-session-exit.
#
# Non-blocking by design — SessionEnd cannot block exit anyway, and the
# value is filesystem-side: paused.md is found in the next session,
# stderr surfaces in the user's terminal on exit, rule-hits drives audit.
#
# Detection scope: tail -n 200 of transcript JSONL is the working window.
# Single jq pass: find last user-input message line (text content, not
# tool_result), slice forward, flatten tool_use entries from assistant
# turns, classify by name + Bash-command-pattern.
#
# Validate patterns (Bash command substring match):
#   node --test, pytest, jest, vitest, npm test, go test, cargo test,
#   bash tests/, tsc, eslint, ruff, clippy, shellcheck — test/lint chain
#   git commit, git push                                — finalization-as-validate
#
# Kill-switch: DISABLE_SESSION_END_CHECK_HOOK=1
# Fail-open on any hiccup.

set -uo pipefail

LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib"
# shellcheck source=/dev/null
source "$LIB_DIR/hook-common.sh" || exit 0

hook_kill_switch SESSION_END_CHECK || exit 0
hook_require_jq || { hook_record_failopen session-end-check jq-missing; exit 0; }

EVENT=$(hook_read_event) || exit 0
TRANSCRIPT=$(printf '%s' "$EVENT" | jq -r '.transcript_path // ""' 2>/dev/null)
CWD=$(printf '%s' "$EVENT" | jq -r '.cwd // ""' 2>/dev/null)
SESSION_ID=$(printf '%s' "$EVENT" | jq -r '.session_id // "unknown"' 2>/dev/null)

[[ -n "$TRANSCRIPT" && -f "$TRANSCRIPT" ]] || exit 0
[[ -n "$CWD" ]] || CWD="$PWD"

# Single jq pass over last 200 lines: find last user-input message,
# slice forward, classify tool_use entries.
RESULT=$(tail -n 200 "$TRANSCRIPT" 2>/dev/null | jq -R -s '
  split("\n") |
  map(select(length > 0) | try fromjson catch null) |
  map(select(. != null)) |
  (map(.type == "user" and ((.message.content // []) | any(.type == "text")))) as $mask |
  ($mask | to_entries | map(select(.value)) | (last // {key: -1}) | .key) as $lastUser |
  .[$lastUser + 1:] |
  map(select(.type == "assistant") | (.message.content // [])) |
  (reduce .[] as $arr ([]; . + $arr)) |
  map(select(.type == "tool_use")) as $tools |
  $tools |
  reduce .[] as $t (
    {mutations: 0, validates: 0, recent: []};
    if ($t.name == "Edit" or $t.name == "Write" or $t.name == "NotebookEdit") then
      .mutations += 1
      | .recent = ((.recent + [{name: $t.name, target: ($t.input.file_path // $t.input.notebook_path // "?")}]) | (if length > 3 then .[length-3:] else . end))
    elif $t.name == "Bash" then
      ($t.input.command // "") as $cmd |
      # Anchor each validate verb to a command position — start of string or
      # right after a shell separator (; && || | newline). Pre-v0.23.11 this was
      # a bare substring test, so `echo "TODO: git commit later"` /
      # `grep "npm test" file` counted as a validation and suppressed the
      # mid-SPINE paused.md checkpoint. A stricter anchor errs toward WRITING
      # the checkpoint (the safe side for this advisory safety-net).
      if ($cmd | test("(^|[;&|\n]+[ \t]*)(node --test|pytest|npm test|jest|vitest|go test|cargo test|bash tests/|tsc |eslint|ruff |clippy|shellcheck|git commit|git push)")) then
        .validates += 1
      else . end
    else . end
  )
' 2>/dev/null)

[[ -n "$RESULT" ]] || exit 0

MUTATIONS=$(printf '%s' "$RESULT" | jq -r '.mutations // 0' 2>/dev/null)
VALIDATES=$(printf '%s' "$RESULT" | jq -r '.validates // 0' 2>/dev/null)

# Trip condition: mutations > 0 AND validates == 0
if [[ "${MUTATIONS:-0}" -gt 0 && "${VALIDATES:-0}" -eq 0 ]]; then
  mkdir -p "$CWD/tasks" 2>/dev/null || exit 0
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || TS="unknown"
  SLUG=$(printf 'session-end-%s' "${SESSION_ID:0:8}")
  PAUSED="$CWD/tasks/${SLUG}-paused.md"

  RECENT_LIST=$(printf '%s' "$RESULT" | jq -r '
    (.recent // []) | map("- \(.name): \(.target)") | join("\n")
  ' 2>/dev/null)

  cat > "$PAUSED" <<EOF
# Paused — mid-SPINE session exit detected

Generated by claudemd \`session-end-check.sh\` at $TS.

The last assistant turn(s) since the final user prompt contained **$MUTATIONS mutation
tool call(s)** (Edit / Write / NotebookEdit) but **0 VALIDATE signals** (test
runner / lint / typecheck / git commit / git push).

Per spec §11 "Session-exit mid-SPINE" HARD: un-VALIDATE'd items MUST NOT be
reported as Done. Re-run the work's verify command before treating any of
these as complete.

## Last mutation tool call(s)

(showing up to the last 3 of $MUTATIONS total)

$RECENT_LIST

## Source

- session_id: $SESSION_ID
- transcript: $TRANSCRIPT
- ts: $TS

## Resume

Run the project's verify command (e.g. \`bash tests/run-all.sh\`,
\`pytest\`, \`cargo test\`, etc.), then either delete this file (verified
green) or convert it to a real \`tasks/<slug>-paused.md\` with the
specific verify command and remaining work.
EOF

  printf '[claudemd] mid-SPINE session-exit: %d unvalidated mutation(s); paused.md → %s\n' \
    "$MUTATIONS" "$PAUSED" >&2

  hook_record session-end-check warn \
    "$(jq -cn --argjson m "$MUTATIONS" --arg p "$PAUSED" '{mutations:$m,paused:$p}' 2>/dev/null)" \
    '§11-session-exit' "$SESSION_ID"
fi

# v0.10.1: drop session-extended-read sentinel for this SID. Hook fail-open
# already tolerates missing/leaked sentinels — this is best-effort GC so
# `~/.claude/.claudemd-state/` doesn't accumulate one file per ended session.
if [[ -n "${SESSION_ID:-}" && "$SESSION_ID" != "unknown" ]]; then
  SAFE_SID=$(printf '%s' "$SESSION_ID" | tr -c '[:alnum:]-' '_')
  rm -f "$HOME/.claude/.claudemd-state/ext-read-${SAFE_SID}.ts" 2>/dev/null || true
fi

# v0.19.2 B1 — §13.2 batch-review cadence advisory.
#
# Mechanizes the operator-facing OPERATOR.md §13.2 line "every 20 L2+ tasks
# OR 30 days (whichever first) — merge overlapping `rule-candidates-*.md`
# entries, promote eligible candidates per §13.2 gates, prune stale entries."
# Pre-this, the cadence was operator-tracked-in-head; if maintainer skipped
# the manual /claudemd-sampling-audit run, the §13.2/§13.3 feedback loop
# went dark.
#
# L2+ heuristic: this session emitted ≥1 rule-hits row with event in
# {deny, warn, deny-repeat} (always-on signals) plus the opt-in
# {structure-advisory, mid-spine-advisory} when their respective Stop scans
# are enabled (TRANSCRIPT_STRUCTURE_SCAN=1 / MID_SPINE_YIELD_SCAN=1).
# In default-OFF posture only the first three fire — sufficient coverage
# (hook denies for §5-hard / §8 / §7 + unvalidated-mutation `warn` from
# this script + same-CI-run retry escalation `deny-repeat` from
# ship-baseline). When operators flip the opt-in scans on, sensitivity
# increases automatically without code change.
#
# Counter file: ~/.claude/.claudemd-state/l2-task-counter. Single-line text
# integer. Increment per L2+ session; at threshold → advisory stderr + reset
# to 0 + audit event. Threshold = 20 per §13.2.
#
# Kill-switch: covered by DISABLE_SESSION_END_CHECK_HOOK at top of file.
# To disable ONLY this sub-feature without disabling the mid-SPINE check:
# DISABLE_BATCH_CADENCE_ADVISORY=1 (sub-flag, env-controlled).
if [[ "${DISABLE_BATCH_CADENCE_ADVISORY:-0}" != "1" ]]; then
  LOG="$HOME/.claude/logs/claudemd.jsonl"
  COUNTER_DIR="$HOME/.claude/.claudemd-state"
  COUNTER_FILE="$COUNTER_DIR/l2-task-counter"
  mkdir -p "$COUNTER_DIR" 2>/dev/null || true
  if [[ -f "$LOG" && -n "${SESSION_ID:-}" && "$SESSION_ID" != "unknown" ]]; then
    # Single jq pass: parse each row, filter to this session_id + L2+ event
    # set, count. -R reads lines, try fromjson catch empty drops malformed.
    # v0.20.1 I2: `tail -n 10000` bound before jq to prevent linear scan cost
    # on oversized rule-hits logs (5MB warn threshold ≈ 50K rows; a single
    # session won't reasonably emit 10K rows, so the tail is a defensive
    # cap with zero behavior change on healthy logs).
    L2_HIT_COUNT=$(tail -n 10000 "$LOG" 2>/dev/null | jq -R -s --arg sid "$SESSION_ID" '
      split("\n")
      | map(select(length > 0) | try fromjson catch empty)
      | map(select(.session_id == $sid))
      | map(select(.event == "deny"
                   or .event == "structure-advisory"
                   or .event == "mid-spine-advisory"
                   or .event == "warn"
                   or .event == "deny-repeat"))
      | length
    ' 2>/dev/null) || L2_HIT_COUNT=0
    [[ "$L2_HIT_COUNT" =~ ^[0-9]+$ ]] || L2_HIT_COUNT=0
    if (( L2_HIT_COUNT > 0 )); then
      CUR=0
      if [[ -r "$COUNTER_FILE" ]]; then
        CUR=$(cat "$COUNTER_FILE" 2>/dev/null || printf '0')
        [[ "$CUR" =~ ^[0-9]+$ ]] || CUR=0
      fi
      NEXT=$((CUR + 1))
      # Threshold: 20 L2+ sessions per OPERATOR.md §13.2 cadence. Test-overridable
      # via CLAUDEMD_BATCH_THRESHOLD (positive integer); other values silently
      # ignored, keeping the cadence stable for operators who env-typo.
      THRESHOLD=20
      if [[ "${CLAUDEMD_BATCH_THRESHOLD:-}" =~ ^[1-9][0-9]*$ ]]; then
        THRESHOLD="$CLAUDEMD_BATCH_THRESHOLD"
      fi
      if (( NEXT >= THRESHOLD )); then
        echo "[claudemd] §13.2 batch-review cadence: ${THRESHOLD} L2+ sessions since last reset — recommend \`/claudemd-sampling-audit\` to feed §13.2 promotion gates + \`/claudemd-rules\` to spot demote candidates." >&2
        echo "  Disable advisory: DISABLE_BATCH_CADENCE_ADVISORY=1" >&2
        printf '0' > "$COUNTER_FILE" 2>/dev/null || true
        EXTRA=$(jq -cn --argjson n "$THRESHOLD" '{l2_sessions:$n}' 2>/dev/null) || EXTRA='null'
        hook_record session-end-check batch-cadence-advisory "$EXTRA" '§13.2-batch-review' "$SESSION_ID"
      else
        printf '%d' "$NEXT" > "$COUNTER_FILE" 2>/dev/null || true
      fi
    fi
  fi
fi

exit 0
