#!/usr/bin/env bash
# session-end-check.sh — SessionEnd hook (v0.9.27 R-N10).
#
# Mechanizes core §11 "Session-exit mid-SPINE" HARD self-rule. At session
# termination, scan the transcript JSONL for mutation tool_use entries
# (Edit / Write / NotebookEdit) since the last user-input message, and
# count VALIDATE signals (Bash with test-runner / lint / typecheck /
# git commit / git push patterns). If mutations > 0 AND validates == 0:
# write a `<cwd>/tasks/<slug>-paused.md` checkpoint, stderr a one-line
# warn, and append a `warn` row to rule-hits.jsonl under §11-session-exit.
#
# Non-blocking by design — SessionEnd cannot block exit anyway, and the
# value is filesystem-side: paused.md is found in the next session,
# stderr surfaces in the user's terminal on exit, rule-hits drives audit.
#
# Detection scope: tail -n 200 of transcript JSONL is the working window.
# Single jq pass: find last user-input message line (text content, not
# tool_result), slice forward, flatten tool_use entries from assistant
# turns, classify by name + Bash-command-pattern.
#
# Validate patterns (Bash command substring match):
#   node --test, pytest, jest, vitest, npm test, go test, cargo test,
#   bash tests/, tsc, eslint, ruff, clippy, shellcheck — test/lint chain
#   git commit, git push                                — finalization-as-validate
#
# Kill-switch: DISABLE_SESSION_END_CHECK_HOOK=1
# Fail-open on any hiccup.

set -uo pipefail

LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib"
# shellcheck source=/dev/null
source "$LIB_DIR/hook-common.sh" || exit 0

hook_kill_switch SESSION_END_CHECK || exit 0
hook_require_jq || { hook_record_failopen session-end-check jq-missing; exit 0; }

EVENT=$(hook_read_event) || exit 0
TRANSCRIPT=$(printf '%s' "$EVENT" | jq -r '.transcript_path // ""' 2>/dev/null)
CWD=$(printf '%s' "$EVENT" | jq -r '.cwd // ""' 2>/dev/null)
SESSION_ID=$(printf '%s' "$EVENT" | jq -r '.session_id // "unknown"' 2>/dev/null)

[[ -n "$TRANSCRIPT" && -f "$TRANSCRIPT" ]] || exit 0
[[ -n "$CWD" ]] || CWD="$PWD"

# Single jq pass over last 200 lines: find last user-input message,
# slice forward, classify tool_use entries.
RESULT=$(tail -n 200 "$TRANSCRIPT" 2>/dev/null | jq -R -s '
  split("\n") |
  map(select(length > 0) | try fromjson catch null) |
  map(select(. != null)) |
  (map(.type == "user" and ((.message.content // []) | any(.type == "text")))) as $mask |
  ($mask | to_entries | map(select(.value)) | (last // {key: -1}) | .key) as $lastUser |
  .[$lastUser + 1:] |
  map(select(.type == "assistant") | (.message.content // [])) |
  (reduce .[] as $arr ([]; . + $arr)) |
  map(select(.type == "tool_use")) as $tools |
  $tools |
  reduce .[] as $t (
    {mutations: 0, validates: 0, recent: []};
    if ($t.name == "Edit" or $t.name == "Write" or $t.name == "NotebookEdit") then
      .mutations += 1
      | .recent = ((.recent + [{name: $t.name, target: ($t.input.file_path // $t.input.notebook_path // "?")}]) | (if length > 3 then .[length-3:] else . end))
    elif $t.name == "Bash" then
      ($t.input.command // "") as $cmd |
      if ($cmd | test("(node --test|pytest|npm test|jest|vitest|go test|cargo test|bash tests/|tsc |eslint|ruff |clippy|shellcheck|git commit|git push)")) then
        .validates += 1
      else . end
    else . end
  )
' 2>/dev/null)

[[ -n "$RESULT" ]] || exit 0

MUTATIONS=$(printf '%s' "$RESULT" | jq -r '.mutations // 0' 2>/dev/null)
VALIDATES=$(printf '%s' "$RESULT" | jq -r '.validates // 0' 2>/dev/null)

# Trip condition: mutations > 0 AND validates == 0
if [[ "${MUTATIONS:-0}" -gt 0 && "${VALIDATES:-0}" -eq 0 ]]; then
  mkdir -p "$CWD/tasks" 2>/dev/null || exit 0
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) || TS="unknown"
  SLUG=$(printf 'session-end-%s' "${SESSION_ID:0:8}")
  PAUSED="$CWD/tasks/${SLUG}-paused.md"

  RECENT_LIST=$(printf '%s' "$RESULT" | jq -r '
    (.recent // []) | map("- \(.name): \(.target)") | join("\n")
  ' 2>/dev/null)

  cat > "$PAUSED" <<EOF
# Paused — mid-SPINE session exit detected

Generated by claudemd \`session-end-check.sh\` at $TS.

The last assistant turn(s) since the final user prompt contained **$MUTATIONS mutation
tool call(s)** (Edit / Write / NotebookEdit) but **0 VALIDATE signals** (test
runner / lint / typecheck / git commit / git push).

Per spec §11 "Session-exit mid-SPINE" HARD: un-VALIDATE'd items MUST NOT be
reported as Done. Re-run the work's verify command before treating any of
these as complete.

## Last mutation tool call(s)

$RECENT_LIST

## Source

- session_id: $SESSION_ID
- transcript: $TRANSCRIPT
- ts: $TS

## Resume

Run the project's verify command (e.g. \`bash tests/run-all.sh\`,
\`pytest\`, \`cargo test\`, etc.), then either delete this file (verified
green) or convert it to a real \`tasks/<slug>-paused.md\` with the
specific verify command and remaining work.
EOF

  printf '[claudemd] mid-SPINE session-exit: %d unvalidated mutation(s); paused.md → %s\n' \
    "$MUTATIONS" "$PAUSED" >&2

  hook_record session-end-check warn \
    "$(jq -cn --argjson m "$MUTATIONS" --arg p "$PAUSED" '{mutations:$m,paused:$p}' 2>/dev/null)" \
    '§11-session-exit' "$SESSION_ID"
fi

exit 0
