// s8-shadow.test.js — the R2 shadow evaluator (scripts/offline-eval/s8-shadow.mjs
// and scripts/offline-eval/s8-ast/), testable without shfmt.
//
// tests/fixtures/s8-ast/<name>.json is what shfmt v3.14.1 printed for the
// command in cases.json. Regenerate one with the pinned binary (sha256 in
// ast-rm.sh's header):
//   printf '%s' "$CMD" | "$SHFMT" --to-json > tests/fixtures/s8-ast/<name>.json
// Three things are pinned here:
//   1. what rm-arm.jq emits for each fixture (the policy);
//   2. the parts of shfmt's JSON the arm reads (operators as strings such as
//      ":?" since 3.14.0, Pos/End byte offsets, node type names), so fixtures
//      regenerated by an shfmt whose schema moved turn this red — and, when
//      SHFMT is set, that the local binary still prints these exact fixtures;
//   3. the runner's pure parsing and classification.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {
  classify,
  parseGateOutput,
  parseAstOutput,
  parseCorpus,
  mentionsRmOrFind,
  gateEnv,
  summarize,
  sample,
} from '../../scripts/offline-eval/s8-shadow.mjs';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const FIX = path.join(REPO, 'tests/fixtures/s8-ast');
const ARM = path.join(REPO, 'scripts/offline-eval/s8-ast/rm-arm.jq');
const DRIVER = path.join(REPO, 'scripts/offline-eval/s8-ast/ast-rm.sh');
const CASES = JSON.parse(fs.readFileSync(path.join(FIX, 'cases.json'), 'utf8'));
const tree = name => JSON.parse(fs.readFileSync(path.join(FIX, `${name}.json`), 'utf8'));
const nodes = (t, type) => {
  const out = [];
  const walk = x => {
    if (Array.isArray(x)) x.forEach(walk);
    else if (x && typeof x === 'object') {
      if (x.Type === type) out.push(x);
      Object.values(x).forEach(walk);
    }
  };
  walk(t);
  return out;
};

function arm(name, args = []) {
  const r = spawnSync('jq', ['-r', ...args, '-f', ARM, path.join(FIX, `${name}.json`)], { encoding: 'utf8' });
  assert.equal(r.status, 0, `jq failed on ${name}: ${r.stderr}`);
  return r.stdout.split('\n').filter(Boolean);
}

// What the arm must emit per fixture. GUARDS is always the first line.
const EXPECT = {
  unguarded: ['GUARDS\t[]', 'DENY\tD'],
  guarded: ['GUARDS\t["D"]'],
  'question-guard': ['GUARDS\t[]', 'DENY\tD'],
  'whitelist-bare': ['GUARDS\t[]', 'DENY\tHOME'],
  dotdot: ['GUARDS\t["D"]', 'DENY\tD'],
  'first-var': ['GUARDS\t["D"]'],
  'mktemp-dominates': ['GUARDS\t[]'],
  'mktemp-subshell': ['GUARDS\t[]', 'DENY\tD'],
  'mktemp-exported': ['GUARDS\t[]', 'DENY\tD'],
  'mktemp-unset': ['GUARDS\t[]', 'DENY\tD'],
  'mktemp-nameref': ['GUARDS\t[]', 'DENY\tD'],
  find: ['GUARDS\t[]', 'DENY\tHOME', 'DENY\tB'],
  wrappers: ['GUARDS\t[]', 'DENY\tX'],
  inner: ['GUARDS\t[]', 'INNER\t9:20', 'INNER\t29:31,32:35,36:41'],
  'quoted-data': ['GUARDS\t[]'],
};

test('s8-ast: every case has a fixture and an expectation, and nothing else does', () => {
  const names = CASES.map(c => c.name).sort();
  assert.deepEqual(Object.keys(EXPECT).sort(), names);
  const files = fs
    .readdirSync(FIX)
    .filter(f => f !== 'cases.json')
    .map(f => f.replace(/\.json$/, ''))
    .sort();
  assert.deepEqual(files, names);
});

for (const c of CASES) {
  test(`s8-ast: rm-arm.jq on "${c.cmd}"`, () => {
    assert.deepEqual(arm(c.name), EXPECT[c.name]);
  });
}

test('s8-ast: INNER spans are byte offsets into the command that bound the child string', () => {
  const cmd = Buffer.from(CASES.find(c => c.name === 'inner').cmd, 'utf8');
  const text = spans =>
    spans
      .split(',')
      .map(s => s.split(':').map(Number))
      .map(([a, b]) => cmd.subarray(a, b).toString('utf8'));
  const inner = arm('inner').filter(l => l.startsWith('INNER\t'));
  assert.deepEqual(text(inner[0].split('\t')[1]), ["'rm -rf $X'"]);
  assert.deepEqual(text(inner[1].split('\t')[1]), ['rm', '-rf', '"\\$Y"']);
});

test('s8-ast: a guard handed down from an outer scan credits the inner rm', () => {
  assert.deepEqual(arm('unguarded', ['--argjson', 'outer', '["D"]']), ['GUARDS\t["D"]']);
});

test('s8-ast: the ablate knob restores prototype-v6 behaviour one piece at a time', () => {
  // v6 never denied a whitelisted name, and credited ${D?} as a guard.
  assert.deepEqual(arm('whitelist-bare', ['--argjson', 'ablate', '["whitelist"]']), ['GUARDS\t[]']);
  assert.deepEqual(arm('question-guard', ['--argjson', 'ablate', '["colon"]']), ['GUARDS\t["D"]']);
  // v6 judged every expansion in a target, those inside $(...) included.
  assert.deepEqual(arm('first-var', ['--argjson', 'ablate', '["firstvar"]']), [
    'GUARDS\t["D"]',
    'DENY\tf',
    'DENY\tR',
  ]);
});

// ---- the shfmt JSON schema the arm depends on -------------------------------

test('shfmt schema: operators are strings (3.14.0+), not the integers older builds print', () => {
  const pe = t => nodes(tree(t), 'ParamExp').find(p => p.Param?.Value === 'D');
  assert.equal(pe('guarded').Exp.Op, ':?');
  assert.equal(pe('question-guard').Exp.Op, '?');
  assert.equal(nodes(tree('mktemp-dominates'), 'BinaryCmd')[0].Op, '&&');
  assert.equal(pe('unguarded').Exp, undefined, 'a bare $D carries no Exp');
  assert.equal(pe('unguarded').Short, true, '$D is Short, ${D} is not');
});

test('shfmt schema: every positioned node carries Pos/End byte offsets', () => {
  let seen = 0;
  for (const c of CASES) {
    const bytes = Buffer.byteLength(c.cmd, 'utf8');
    const walk = x => {
      if (Array.isArray(x)) return x.forEach(walk);
      if (!x || typeof x !== 'object') return;
      if (x.Pos && x.End) {
        seen++;
        assert.equal(typeof x.Pos.Offset, 'number');
        assert.equal(typeof x.End.Offset, 'number');
        assert.ok(
          x.Pos.Offset <= x.End.Offset && x.End.Offset <= bytes,
          `${c.name}: offsets inside the command`
        );
      }
      Object.values(x).forEach(walk);
    };
    walk(tree(c.name));
  }
  assert.ok(seen > 100, `offsets checked on ${seen} nodes`);
  const lit = nodes(tree('unguarded'), 'Lit').find(l => l.Value === 'rm');
  assert.deepEqual([lit.Pos.Offset, lit.End.Offset], [0, 2]);
});

test('shfmt schema: the node shapes the arm walks', () => {
  const root = tree('mktemp-exported');
  assert.equal(root.Type, 'File');
  assert.ok(Array.isArray(root.Stmts));
  const call = nodes(root, 'CallExpr')[0];
  const assign = call.Assigns[0];
  assert.equal(assign.Name.Value, 'D');
  assert.equal(assign.Value.Parts[0].Type, 'CmdSubst');
  assert.equal(assign.Value.Parts[0].Stmts[0].Cmd.Args[0].Parts[0].Value, 'mktemp');
  const decl = nodes(root, 'DeclClause')[0];
  assert.equal(decl.Variant.Value, 'export');
  assert.equal(decl.Args[0].Naked, true);
  assert.equal(decl.Args[0].Name.Value, 'D');
  assert.equal(nodes(tree('mktemp-dominates'), 'DblQuoted')[0].Parts[0].Type, 'CmdSubst');
  assert.equal(nodes(tree('mktemp-subshell'), 'Subshell').length, 1);
  assert.equal(nodes(tree('quoted-data'), 'SglQuoted')[0].Value, 'x; rm -rf $f');
  assert.equal(nodes(tree('dotdot'), 'DblQuoted')[0].Parts[1].Value, '/../x');
});

test('shfmt schema: the local SHFMT, when set, still prints these exact fixtures', t => {
  const shfmt = process.env.SHFMT;
  if (!shfmt || !fs.existsSync(shfmt)) {
    t.skip('SHFMT not set; the committed fixtures are checked above');
    return;
  }
  for (const c of CASES) {
    const r = spawnSync(shfmt, ['--to-json'], { input: c.cmd, encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
    assert.deepEqual(JSON.parse(r.stdout), tree(c.name), `${c.name}: shfmt output moved`);
  }
});

// ---- the driver's refusals and switches (a stub stands in for shfmt) --------

function withStub(fn) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'claudemd-test-r2shadow-'));
  try {
    const stub = path.join(dir, 'shfmt');
    fs.writeFileSync(
      stub,
      '#!/bin/sh\ncase "$1" in\n  --version) echo "${STUB_VERSION:-v3.14.1}" ;;\n' +
        '  --to-json) cat >/dev/null; [ -n "$STUB_JSON" ] || exit 1\n' +
        '    if [ "$STUB_JSON" = broken ]; then echo "{"; else cat "$STUB_JSON"; fi ;;\nesac\n'
    );
    fs.chmodSync(stub, 0o755);
    fn(stub);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}
const drive = (cmd, env) =>
  spawnSync('bash', [DRIVER], { input: cmd, encoding: 'utf8', env: { ...process.env, ...env } });

test('ast-rm.sh: refuses (exit 2) without shfmt, or with one older than 3.14.0', () => {
  const none = drive('rm -rf "$D"', { SHFMT: '' });
  assert.equal(none.status, 2);
  assert.match(none.stderr, /set SHFMT/);
  withStub(stub => {
    const old = drive('rm -rf "$D"', { SHFMT: stub, STUB_VERSION: 'v3.13.1' });
    assert.equal(old.status, 2);
    assert.match(old.stderr, /older than 3\.14\.0/);
    assert.equal(drive('rm -rf "$D"', { SHFMT: stub, STUB_VERSION: 'devel' }).status, 2);
  });
});

test('ast-rm.sh: verdict lines, the gate switches, and a failing arm reads as error', () => {
  withStub(stub => {
    const env = { SHFMT: stub, STUB_JSON: path.join(FIX, 'unguarded.json') };
    assert.equal(drive('x', env).stdout, 'deny D\n');
    assert.equal(drive('x', { ...env, STUB_JSON: path.join(FIX, 'guarded.json') }).stdout, 'allow\n');
    assert.equal(drive('x', { ...env, STUB_JSON: '' }).stdout, 'parse-error\n');
    assert.equal(drive('rm -rf $D [allow-rm-rf-var]', env).stdout, 'allow\n');
    assert.equal(drive('x', { ...env, DISABLE_PRE_BASH_SAFETY_HOOK: '1' }).stdout, 'allow\n');
    assert.equal(
      drive('x', { ...env, DISABLE_PRE_BASH_SAFETY_HOOK: '1', S8_AST_ABLATE: 'knobs' }).stdout,
      'deny D\n'
    );
    const bad = drive('x', { ...env, STUB_JSON: 'broken' });
    assert.equal(bad.stdout, 'error\n', 'jq failing must not read as "no finding"');
    assert.equal(bad.status, 3);
  });
});

// ---- the runner's pure parts ------------------------------------------------

const gateDeny = bullets =>
  JSON.stringify({
    hookSpecificOutput: {
      permissionDecision: 'deny',
      permissionDecisionReason: `§8 SAFETY: denied Bash invocation:\n${bullets.map(b => `  - ${b}`).join('\n')}\n\nrm -r/-f on a $VAR …`,
    },
  });

test('s8-shadow: parseGateOutput reads the rm bullets and their variables', () => {
  assert.deepEqual(parseGateOutput(''), { verdict: 'allow', rm: false, vars: [], other: false });
  assert.equal(parseGateOutput('', 1).verdict, 'error', 'a crash with empty stdout is not an allow');
  assert.equal(parseGateOutput('not json').verdict, 'error');
  const g = parseGateOutput(
    gateDeny([
      'rm -rf with unvalidated $D',
      'rm -f $HOME with no subpath (whitelist permits $HOME/sub, not bare $HOME)',
      'rm -rf $TMPDIR whose only subpath is $x: the gate reads $x as empty',
      'find … -delete/-exec rm on bare $PWD with no selection primary — it deletes everything under it.',
      'rm --recursive target leaves $S through a `..` component.',
    ])
  );
  assert.deepEqual(g, { verdict: 'deny', rm: true, vars: ['D', 'HOME', 'PWD', 'S', 'TMPDIR'], other: false });
  const npx = parseGateOutput(gateDeny(['npx unpinned package (no lockfile/local in <no-cwd>): foo']));
  assert.deepEqual(npx, { verdict: 'deny', rm: false, vars: [], other: true });
  const both = parseGateOutput(gateDeny(['rm -rf with unvalidated $X', 'npx unpinned package: foo']));
  assert.deepEqual([both.rm, both.other, both.vars], [true, true, ['X']]);
});

test('s8-shadow: parseAstOutput', () => {
  assert.deepEqual(parseAstOutput('allow\n'), { verdict: 'allow', vars: [] });
  assert.deepEqual(parseAstOutput('deny SP D\n'), { verdict: 'deny', vars: ['D', 'SP'] });
  assert.deepEqual(parseAstOutput('parse-error\n'), { verdict: 'parse-error', vars: [] });
  assert.equal(parseAstOutput('error\n', 3).verdict, 'error');
  assert.equal(parseAstOutput('deny D\n', 2).verdict, 'error', 'a non-zero exit is never a verdict');
});

test('s8-shadow: classify covers every class, and a non-rm gate deny is an rm allow', () => {
  const G = (verdict, rm) => ({ verdict, rm, vars: [], other: !rm });
  const A = verdict => ({ verdict, vars: [] });
  assert.equal(classify(G('deny', true), A('deny')), 'both-deny');
  assert.equal(classify(G('allow', false), A('allow')), 'both-allow');
  assert.equal(classify(G('deny', true), A('allow')), 'gate-only-deny');
  assert.equal(classify(G('allow', false), A('deny')), 'ast-only-deny');
  assert.equal(classify(G('deny', false), A('deny')), 'ast-only-deny');
  assert.equal(classify(G('deny', false), A('allow')), 'both-allow');
  assert.equal(classify(G('deny', true), A('parse-error')), 'ast-parse-error');
  assert.equal(classify(G('error', false), A('deny')), 'error');
  assert.equal(classify(G('allow', false), A('error')), 'error');
});

test('s8-shadow: summarize counts classes, labels and the residual rows', () => {
  const row = (label, cls, gv, av) => ({
    source: 'corpus',
    label,
    class: cls,
    gate: { verdict: gv, rm: gv === 'deny', vars: gv === 'deny' ? ['X'] : [] },
    ast: { verdict: av, vars: av === 'deny' ? ['Y'] : [] },
    msGate: 10,
    msAst: 2,
  });
  const s = summarize([
    row('xfn', 'ast-only-deny', 'allow', 'deny'),
    row('xfn', 'both-allow', 'allow', 'allow'),
    row('xfp', 'gate-only-deny', 'deny', 'allow'),
    row('pass', 'both-allow', 'allow', 'allow'),
    row('deny', 'both-deny', 'deny', 'deny'),
  ]);
  assert.equal(s.table['ast-only-deny'], 1);
  assert.equal(s.byLabel.xfn['both-allow'], 1);
  assert.deepEqual(s.residuals.xfnAstDeny, { of: 2, n: 1 });
  assert.deepEqual(s.residuals.xfpAstAllow, { of: 1, n: 1 });
  assert.deepEqual(s.residuals.passAstDeny, { of: 1, n: 0 });
  assert.equal(s.bothDenyVarsDiffer, 1, 'X vs Y');
  assert.equal(s.latencyMs.gate.p50, 10);
});

test('s8-shadow: corpus parsing, the rm/find filter, the gate environment, the sample', () => {
  const rows = parseCorpus('# c\n\npass\tn1\trm -rf a__NL__b\t\nxfn\tn2\tfind . -delete\t-HOME X=1\n');
  assert.deepEqual(
    rows.map(r => [r.label, r.command, r.env]),
    [
      ['pass', 'rm -rf a\nb', ''],
      ['xfn', 'find . -delete', '-HOME X=1'],
    ]
  );
  for (const c of ['rm -rf x', '/bin/rm -f x', '\\rm x', 'a && find . -name y', 'x\nrm y'])
    assert.ok(mentionsRmOrFind(c), c);
  for (const c of ['docker run --rm x', 'rmdir x', 'node find-binary.js', 'arr.find(x)', 'echo 8-rm-rf-var'])
    assert.ok(!mentionsRmOrFind(c), c);
  // The gate's environment: every claudemd knob scrubbed, the sandbox paths and
  // telemetry-off set, then the corpus row's own env column applied.
  const env = gateEnv(
    {
      PATH: '/bin',
      DISABLE_RULE_HITS_LOG: '0',
      DISABLE_X_HOOK: '1',
      CLAUDEMD_Y: '1',
      BASH_READONLY_FAST_PATH: '1',
      BASH_SAFETY_INDIRECT_CALL: '1',
      SHFMT: '/s',
    },
    { home: '/h', tmpdir: '/t' },
    '-PATH BASH_SAFETY_INDIRECT_CALL=0'
  );
  assert.deepEqual(Object.keys(env).sort(), [
    'BASH_SAFETY_INDIRECT_CALL',
    'DISABLE_RULE_HITS_LOG',
    'HOME',
    'SHFMT',
    'TMPDIR',
  ]);
  assert.deepEqual(
    [env.HOME, env.TMPDIR, env.DISABLE_RULE_HITS_LOG, env.BASH_SAFETY_INDIRECT_CALL, env.SHFMT],
    ['/h', '/t', '1', '0', '/s']
  );
  const xs = Array.from({ length: 50 }, (_, i) => i);
  assert.deepEqual(sample(xs, 5), sample(xs, 5), 'fixed seed');
  assert.equal(new Set(sample(xs, 50)).size, 50);
});
